name: python-app-1-cicd

on:
  push:
    paths:
        - src/**
    branches:
        - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - 
        name: Shorten Commit ID
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::06}" >> "$GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: johnmonteir0/python-app-1:${{ env.COMMIT_ID }}

    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - 
        name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app-1/values-dev.yaml
      
      -
        name: Commit changes
        uses: Endbug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      - 
        name: Install argocd
        shell: bash
        run: |
          curl  -ksSL -o argocd https://argocd.767397786711.realhandsonlabs.net/download/argocd-linux-amd64
          sudo chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - 
        name: Argocd login
        shell: bash
        run: |
          argocd login argocd.767397786711.realhandsonlabs.net \
           --insecure \
           --grpc-web \
           --username admin \
           --password ${{  secrets.ARGOCD_PASSWORD }}


      - 
        name: Ensure argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/j0hnmonteir0/python-app-1.git"
          argocd repo list | grep -q $repo || argocd repo add $repo


          # Creates the argocd app
          argocd app get python-app-1 || argocd app create python-app-1 \
            --repo $repo \
            --path charts/python-app-1 \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision main \
            --sync-option CreateNamespace=true

        
      - 
        name: Argocd app sync
        shell: bash
        run: |
          argocd app sync python-app-1
          argocd app wait python-app-1 --timeout 180